name: sqlupdate

on:
  push:
    branches:
      - updatesql  # updatesqlブランチを監視
    paths:
      - Database/Register/datum/addbook.txt  # addbook.txtの変更のみをトリガー

jobs:
  merge-execute-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # リポジトリをチェックアウト
      - name: Checkout updatesql branch
        uses: actions/checkout@v2
        with:
          ref: updatesql

      # Pythonをセットアップ
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      # 必要なPythonパッケージをインストール
      - name: Install Python dependencies
        run: |
           pip install SQLAlchemy bs4 requests

      # Pythonプログラムを実行
      - name: Run Python program
        run: |
          python -m Database.Register.register_actions
        continue-on-error: false  # エラーが発生したらここで停止
      
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated update via GitHub Actions" || echo "No changes to commit"
          git push origin updatesql

      - name: Checkout updatesql branch
        uses: actions/checkout@v2
        with:
          ref: release

      # releaseブランチをマージ
      - name: Merge updatesql into release
        run: |
          git pull origin
          git fetch origin updatesql
          git merge origin/updatesql --no-ff -m "add book"
      

      # エラーが発生した場合はワークフローを終了
      - name: Exit workflow on failure
        if: failure()  # エラーが発生した場合にのみ実行
        run: exit 1  # ワークフローを終了させる
