name: sqlupdate

on:
  push:
    branches:
      - updatesql
    paths:
      - Database/Register/datum/addbook.txt

jobs:
  update-db:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the `updatesql` branch
      - name: Checkout updatesql branch
        uses: actions/checkout@v2
        with:
          ref: updatesql
          fetch-depth: 0

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      # 3. Install dependencies
      - name: Install Python dependencies
        run: |
          pip install SQLAlchemy bs4 requests
      # 4. Run Python script
      - name: Run Python program
        run: |
          python -m Database.Register.register_actions
          
      - name: push sql origin
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Database/ompooscores.db
          git commit -m "Automated update via GitHub Actions" || echo "No changes to commit"
          git push origin updatesql
      # 5. Checkout the `release` branch
      - name: Checkout release branch
        run: |
          git fetch origin
          git checkout -b release origin/release 
          git checkout origin/updatesql -- Database/ompooscores.db -- Src/Static/notice.json
    
      # 7. Commit and push changes to `release`
      - name: Commit and push changes
        run: |
          git config --global user.name "${{ secrets.GITHUBNAME }}"
          git config --global user.email "${{ secrets.EMAIL }}"
          git add Database/ompooscores.db Src/Static/notice.json
          git commit -m "Update ompooscores.db after Python script execution" || echo "No changes to commit"
          git push origin release
