name: sqlupdate

on:
  push:
    branches:
      - updatesql
    paths:
      - Database/Register/datum/addbook.txt

jobs:
  process-updatesql:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 1. Checkout updatesql branch
      - name: Checkout updatesql branch
        uses: actions/checkout@v2
        with:
          ref: updatesql

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      # 3. Install dependencies
      - name: Install Python dependencies
        run: |
          pip install SQLAlchemy bs4 requests

      # 4. Run Python script
      - name: Run Python program
        run: |
          python -m Database.Register.register_actions
        continue-on-error: false
          
  merge-to-release:
    runs-on: ubuntu-latest
    needs: process-updatesql  # `process-updatesql` ジョブが完了してから実行
    permissions:
      contents: write
    steps:
      # 1. Checkout release branch
      - name: Checkout updatesql branch
        uses: actions/checkout@v2
        with:
          ref: updatesql
      # 3. release ブランチにファイルをコピーして push
      - name: Push ompooscore.db to release
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin release
        

      # 5. Commit changes
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated update via GitHub Actions" || echo "No changes to commit"
          git push origin updatesql

      # 3. release ブランチにファイルをコピーして push
      - name: Push ompooscore.db to release
        run: |
          git add Database/ompooscores.db
          git commit -m "Update ompooscores.db"
          git push origin release
