name: sqlupdate

on:
  push:
    branches:
      - updatesql  # updatesqlブランチを監視
    paths:
      - addbook.txt  # addbook.txtの変更のみをトリガー

jobs:
  merge-execute-push:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout updatesql branch
        uses: actions/checkout@v2
        with:
          ref: updatesql

      # releaseブランチをマージ
      - name: Merge release into updatesql
        run: |
          git config --global user.name "scoreadd"
          git config --global user.email "ompooscoremanager@users.noreply.github.com"
          git fetch origin release
          git merge origin/release --no-ff -m "Merged release into updatesql via GitHub Actions"

      # Pythonをセットアップ
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      # 必要なPythonパッケージをインストール
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      # Pythonプログラムを実行
      - name: Run Python program
        run: |
          python your_program.py  # your_program.py を実行
        continue-on-error: false  # エラーが発生したらここで停止

      # エラー時にメールを送信
      - name: Send email on error
        if: failure()  # このジョブが失敗した場合のみ実行
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.example.com  # SMTPサーバーのアドレス
          server_port: 587                  # SMTPポート（通常587）
          username: "${{ secrets.EMAIL }}" # 送信元のメールアドレス
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "GitHub Actions Error Notification"
          body: "An error occurred during the workflow execution. Please check the logs."
          to: "${{ secrets.EMAIL }}"     # 受信者のメールアドレス
          from: "${{ secrets.EMAIL }}"     # 送信者のメールアドレス

      # エラーが発生した場合はワークフローを終了
      - name: Exit workflow on failure
        if: failure()  # エラーが発生した場合にのみ実行
        run: exit 1  # ワークフローを終了させる
