name: sqlupdate

on:
  push:
    branches:
      - updatesql  # updatesqlブランチを監視
    paths:
      - Database/Register/datum/addbook.txt  # addbook.txtの変更のみをトリガー

jobs:
  merge-execute-push:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout updatesql branch
        uses: actions/checkout@v2
        with:
          ref: updatesql

      # Pythonをセットアップ
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      # 必要なPythonパッケージをインストール
      - name: Install Python dependencies
        run: |
          pip install flask
          pip install flask-sqlalchemy
          pip install bs4

      # Pythonプログラムを実行
      - name: Run Python program
        run: |
          python -m Database.Register.register_actions
        continue-on-error: false  # エラーが発生したらここで停止

      # - name: Checkout updatesql branch
      #   uses: actions/checkout@v2
      #   with:
      #     ref: release

      # # releaseブランチをマージ
      # - name: Merge updatesql into release
      #   run: |
      #     git config --global user.name "scoreadd"
      #     git config --global user.email "ompooscoremanager@users.noreply.github.com"
      #     git fetch origin updatesql
      #     git merge origin/updatesql --no-ff -m "Merged updatesql into updatesql via GitHub Actions"
      

      # エラーが発生した場合はワークフローを終了
      - name: Exit workflow on failure
        if: failure()  # エラーが発生した場合にのみ実行
        run: exit 1  # ワークフローを終了させる
